version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nuxt-dependencies:
        patterns:
          - "nuxt*"
          - "@nuxt*"
          - "@vue*"
          - "vue*"
      tooling-dependencies:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "typescript-eslint*"
          - "@typescript-eslint*"
          - "prettier*"
          - "knip*"
          - "husky"
          - "lint-staged"
