import {defineField, defineType} from 'sanity'
import {isAdministrator} from './auth'

export const guide = defineType({
  name: 'guide',
  title: 'Guide',
  type: 'document',
  fieldsets: [{name: 'admin', title: 'Admin Metadata'}],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{type: 'category'}],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'tag'}]}],
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'array',
      of: [{type: 'block'}],
    }),
    defineField({
      name: 'isFeatured',
      title: 'Is Featured',
      type: 'boolean',
      description: 'Marks this guide as featured on the home page.',
      fieldset: 'admin',
      initialValue: false,
      readOnly: ({currentUser}) => !isAdministrator(currentUser ?? undefined),
    }),
    defineField({
      name: 'isUserSubmitted',
      title: 'Is User Submitted',
      type: 'boolean',
      description: 'Indicates if this guide was submitted by a user and is pending review.',
      fieldset: 'admin',
      initialValue: false,
    }),
    defineField({
      name: 'submitterId',
      title: 'Submitter ID',
      type: 'string',
      description: 'The D1 User ID of the person who submitted this guide.',
      fieldset: 'admin',
      readOnly: true,
      hidden: ({document}) => !document?.isUserSubmitted,
    }),
    defineField({
      name: 'isHiddenByModeration',
      title: 'Hidden By Moderation',
      type: 'boolean',
      description: 'Soft-delete flag for moderation. Checked by edge proxy to hide guides.',
      fieldset: 'admin',
      initialValue: false,
      readOnly: ({currentUser}) => !isAdministrator(currentUser ?? undefined),
    }),
  ],
})
